### ISSUE TITLE
Meeting Jan 21, 2022 action items

### ISSUE THREAD

**Issue by hoangthienan95** [corradin-lab/genetic-compensation#6]
An
- [ ] Email the authors  - Where's SKATO?
- [ ] If not use SKATO, adjust the SKAT threshold (8e-9)
- [ ] Ask Olivia about heritability
- [ ] Generate detailed gene-pheno table for only the 384 genes (filtering table from step 1)
- [ ] Generate phenotype info table for only the phenotypes  involved with the 384 genes 

Mohamed

- [x] iPSC gene expression
- [x] Compare ClinVar vs An's list
- [x] Look at whether genes have paralogs

**Comment by brolosy** [comment]
Hi An,

I have now uploaded a couple of files in two different issues, the first are TPMs for gene expression in iPSCs (and human fibroblasts, which are another potential model we could use). 

I also added another issue (paralogous genes) which has a comma delimited text file where each gene is connected to its potential paralogous genes.  Genes which don't have paralogs have a blank after the comma.  In the first colomn, some genes will be repeated as they have multiple paralogs.

I have used this information and merged it with the table you generated from step 2 to identify genes that are interesting and expressed in iPSCs (TPM >10) and have paralogs (see attached).  This makes us end with 129 genes from this analysis (I actually relaxed the threshold of "constraint" from 0.75 to 0.5 to have more genes (with he 0,75 constraint threshold there are only 64 genes) but we can keep this in mind as we decide on the final list of 200-300 genes from all datasets which we will do the Perturb-seq on.  Can you add to the attached file the SKAT-O p-values for LoF and missense from genebass?

There is also little overlap with the data from ClinVar but I think that is expected and is not something to worry about.

[First analysis step 3 file.xlsx](https://github.com/corradin-lab/genetic-compensation/files/7975623/First.analysis.step.3.file.xlsx)

**Comment by hoangthienan95** [comment]
Hi Mohamed,

I have uploaded the files for the analyses we have done so far at the gene level. Since we discussed today about changing some parameters + adding some more filters, I have tried to make this list as inclusive as possible. I have incorporated the iPSC and HFF expression, along with the paralog information (column `has_paralog`)

These genes have **ONLY** been filtered for:

1. SKAT p-value < 2.5e-8
2. oe_lof_div_oe_mis_pphen > 0.5

File with gene level info (each gene one row): 
- [genes_all_info_SKAT-filter-2.5e8_constraint-filter-0.5_Feb4.tsv](https://github.com/corradin-lab/genetic-compensation/blob/main/notebooks/analyses/result/Feb4/genes_all_info_SKAT-filter-2.5e8_constraint-filter-0.5_Feb4.tsv)

File with gene + pheno level info (each gene-phenotype pair one row): 
- [gene_pheno_all_info_SKAT-filter-2.5e8_constraint-filter-0.5_Feb4.tsv](https://github.com/corradin-lab/genetic-compensation/blob/main/notebooks/analyses/result/Feb4/gene_pheno_all_info_SKAT-filter-2.5e8_constraint-filter-0.5_Feb4.tsv)
